import back_card from "./assets/cards/back_card.svg";
import clubs_2 from "./assets/cards/clubs_2.svg";
import clubs_3 from "./assets/cards/clubs_3.svg";
import clubs_4 from "./assets/cards/clubs_4.svg";
import clubs_5 from "./assets/cards/clubs_5.svg";
import clubs_6 from "./assets/cards/clubs_6.svg";
import clubs_7 from "./assets/cards/clubs_7.svg";
import clubs_8 from "./assets/cards/clubs_8.svg";
import clubs_9 from "./assets/cards/clubs_9.svg";
import clubs_10 from "./assets/cards/clubs_9.svg";
import clubs_ace from "./assets/cards/clubs_ace.svg";
import clubs_jack from "./assets/cards/clubs_jack.svg";
import clubs_king from "./assets/cards/clubs_king.svg";
import clubs_queen from "./assets/cards/clubs_queen.svg";
import diamonds_2 from "./assets/cards/diamonds_2.svg";
import diamonds_3 from "./assets/cards/diamonds_3.svg";
import diamonds_4 from "./assets/cards/diamonds_4.svg";
import diamonds_5 from "./assets/cards/diamonds_5.svg";
import diamonds_6 from "./assets/cards/diamonds_6.svg";
import diamonds_7 from "./assets/cards/diamonds_7.svg";
import diamonds_8 from "./assets/cards/diamonds_8.svg";
import diamonds_9 from "./assets/cards/diamonds_9.svg";
import diamonds_10 from "./assets/cards/diamonds_9.svg";
import diamonds_ace from "./assets/cards/diamonds_ace.svg";
import diamonds_jack from "./assets/cards/diamonds_jack.svg";
import diamonds_king from "./assets/cards/diamonds_king.svg";
import diamonds_queen from "./assets/cards/diamonds_queen.svg";
import spades_2 from "./assets/cards/spades_2.svg";
import spades_3 from "./assets/cards/spades_3.svg";
import spades_4 from "./assets/cards/spades_4.svg";
import spades_5 from "./assets/cards/spades_5.svg";
import spades_6 from "./assets/cards/spades_6.svg";
import spades_7 from "./assets/cards/spades_7.svg";
import spades_8 from "./assets/cards/spades_8.svg";
import spades_9 from "./assets/cards/spades_9.svg";
import spades_10 from "./assets/cards/spades_9.svg";
import spades_ace from "./assets/cards/spades_ace.svg";
import spades_jack from "./assets/cards/spades_jack.svg";
import spades_king from "./assets/cards/spades_king.svg";
import spades_queen from "./assets/cards/spades_queen.svg";
import hearts_2 from "./assets/cards/hearts_2.svg";
import hearts_3 from "./assets/cards/hearts_3.svg";
import hearts_4 from "./assets/cards/hearts_4.svg";
import hearts_5 from "./assets/cards/hearts_5.svg";
import hearts_6 from "./assets/cards/hearts_6.svg";
import hearts_7 from "./assets/cards/hearts_7.svg";
import hearts_8 from "./assets/cards/hearts_8.svg";
import hearts_9 from "./assets/cards/hearts_9.svg";
import hearts_10 from "./assets/cards/hearts_9.svg";
import hearts_ace from "./assets/cards/hearts_ace.svg";
import hearts_jack from "./assets/cards/hearts_jack.svg";
import hearts_king from "./assets/cards/hearts_king.svg";
import hearts_queen from "./assets/cards/hearts_queen.svg";

export { default as back_card } from "./assets/cards/back_card.svg";
export { default as clubs_2 } from "./assets/cards/clubs_2.svg";
export { default as clubs_3 } from "./assets/cards/clubs_3.svg";
export { default as clubs_4 } from "./assets/cards/clubs_4.svg";
export { default as clubs_5 } from "./assets/cards/clubs_5.svg";
export { default as clubs_6 } from "./assets/cards/clubs_6.svg";
export { default as clubs_7 } from "./assets/cards/clubs_7.svg";
export { default as clubs_8 } from "./assets/cards/clubs_8.svg";
export { default as clubs_9 } from "./assets/cards/clubs_9.svg";
export { default as clubs_10 } from "./assets/cards/clubs_10.svg";
export { default as clubs_ace } from "./assets/cards/clubs_ace.svg";
export { default as clubs_jack } from "./assets/cards/clubs_jack.svg";
export { default as clubs_king } from "./assets/cards/clubs_king.svg";
export { default as clubs_queen } from "./assets/cards/clubs_queen.svg";

export { default as diamonds_2 } from "./assets/cards/diamonds_2.svg";
export { default as diamonds_3 } from "./assets/cards/diamonds_3.svg";
export { default as diamonds_4 } from "./assets/cards/diamonds_4.svg";
export { default as diamonds_5 } from "./assets/cards/diamonds_5.svg";
export { default as diamonds_6 } from "./assets/cards/diamonds_6.svg";
export { default as diamonds_7 } from "./assets/cards/diamonds_7.svg";
export { default as diamonds_8 } from "./assets/cards/diamonds_8.svg";
export { default as diamonds_9 } from "./assets/cards/diamonds_9.svg";
export { default as diamonds_10 } from "./assets/cards/diamonds_10.svg";
export { default as diamonds_ace } from "./assets/cards/diamonds_ace.svg";
export { default as diamonds_jack } from "./assets/cards/diamonds_jack.svg";
export { default as diamonds_king } from "./assets/cards/diamonds_king.svg";
export { default as diamonds_queen } from "./assets/cards/diamonds_queen.svg";

export { default as hearts_2 } from "./assets/cards/hearts_2.svg";
export { default as hearts_3 } from "./assets/cards/hearts_3.svg";
export { default as hearts_4 } from "./assets/cards/hearts_4.svg";
export { default as hearts_5 } from "./assets/cards/hearts_5.svg";
export { default as hearts_6 } from "./assets/cards/hearts_6.svg";
export { default as hearts_7 } from "./assets/cards/hearts_7.svg";
export { default as hearts_8 } from "./assets/cards/hearts_8.svg";
export { default as hearts_9 } from "./assets/cards/hearts_9.svg";
export { default as hearts_10 } from "./assets/cards/hearts_10.svg";
export { default as hearts_ace } from "./assets/cards/hearts_ace.svg";
export { default as hearts_jack } from "./assets/cards/hearts_jack.svg";
export { default as hearts_king } from "./assets/cards/hearts_king.svg";
export { default as hearts_queen } from "./assets/cards/hearts_queen.svg";

export { default as spades_2 } from "./assets/cards/spades_2.svg";
export { default as spades_3 } from "./assets/cards/spades_3.svg";
export { default as spades_4 } from "./assets/cards/spades_4.svg";
export { default as spades_5 } from "./assets/cards/spades_5.svg";
export { default as spades_6 } from "./assets/cards/spades_6.svg";
export { default as spades_7 } from "./assets/cards/spades_7.svg";
export { default as spades_8 } from "./assets/cards/spades_8.svg";
export { default as spades_9 } from "./assets/cards/spades_9.svg";
export { default as spades_10 } from "./assets/cards/spades_10.svg";
export { default as spades_ace } from "./assets/cards/spades_ace.svg";
export { default as spades_jack } from "./assets/cards/spades_jack.svg";
export { default as spades_king } from "./assets/cards/spades_king.svg";
export { default as spades_queen } from "./assets/cards/spades_queen.svg";